Graylog2/graylog-plugin-integrations

src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoParser.java
src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoTCPInput.java
src/test/java/org.graylog.integrations/inputs/paloalto/PaloAltoCodecTest.java

Fix Palo Alto input parsing issue

---

src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoParser.java
src/test/java/org.graylog.integrations/inputs/paloalto/PaloAltoCodecTest.java

Use actual CSV parser to correctly handle quoted values

---

pom.xml
src/main/java/org/graylog/integrations/aws/AWSConfigSettings.java
src/main/java/org/graylog/integrations/aws/CloudWatchService.java
src/main/java/org/graylog/integrations/aws/Main.java
src/main/java/org/graylog/integrations/aws/UserCredentials.java

Add AWS CloudWatch functionality for Milestone 1

Aws cloudwatch client

---

pom.xml
src/main/java/org/graylog/integrations/aws/KinesisService.java
src/main/java/org/graylog/integrations/aws/Main.java
src/main/java/org/graylog/integrations/aws/service/AWSService.java
src/test/java/org.graylog.integrations/aws/KinesisServiceTest.java

Add retrievelogs for Kinesis Healthcheck

---

src/main/java/org/graylog/integrations/IntegrationsModule.java
src/main/java/org/graylog/integrations/aws/AWSPermissions.java
src/main/java/org/graylog/integrations/aws/resources/AWSResource.java

Aws permissions check

---

yarn.lock

Continuation of #119 to integrate into AWS branch

AWS lockfile

---

src/main/java/org/graylog/integrations/aws/resources/AWSResource.java

Update comment blocks

---

src/web/aws-cloudwatch/CloudWatch.jsx
src/web/aws-cloudwatch/StepReview.jsx
src/web/common/Routes.js

Allows the Input to be saved and redirects to the `/system/inputs` administration page

API Save Input

---

pom.xml
src/web/aws/InputConfiguration.jsx
src/web/index.jsx

Provides us the ability to create custom experiences in the server.
Related PR: https://github.com/Graylog2/graylog2-server/pull/6147

Adding match function to pluginmanifest

---

src/web/aws-cloudwatch/CloudWatch.jsx
src/web/aws-cloudwatch/CloudWatchApp.jsx
src/web/aws-cloudwatch/StepAuthorize.jsx
src/web/aws-cloudwatch/StepReview.jsx
src/web/common/Routes.js

Use `ConfirmLeaveDialog` common component to confirm if the user wants to leave setup
Related to https://github.com/Graylog2/graylog2-server/pull/6165
closes #107

Unload Confirmation Dialog

---

package.json
src/web/aws-cloudwatch/FormAdvancedOptions.jsx
src/web/aws-cloudwatch/StepAuthorize.jsx
src/web/aws-cloudwatch/StepReview.jsx
src/web/common/ValidatedInput.jsx
yarn.lock

This replaces Emotion with [styled-components](https://www.styled-components.com/) which i feel has better documentation and seems to have a more active community

Remove emotion and use styled-components

---

src/web/aws-cloudwatch/FormAdvancedOptions.jsx
src/web/aws-cloudwatch/StepReview.jsx
src/web/aws-cloudwatch/context/default_settings.js

Updated the Enable Throttling option to be contained in a single element with context to the rate of throttle.
Closes #159 
Closes #156

Update Throttling advanced option

---

src/web/aws-cloudwatch/StepAuthorize.jsx
src/web/common/MaskedInput.jsx
src/web/common/ValidatedInput.jsx

Create an input that have be toggled to display text or mask it such as a password.
Closes #104

Create input with togglable masking

---

src/main/java/org/graylog/integrations/aws/service/CloudWatchService.java
src/main/java/org/graylog/integrations/aws/service/KinesisService.java

Add addSubscriptionFilter to CloudwatchService

---

src/web/common/ValidatedInput.jsx

Allows user to go back to Authorize step and Region will be properly selected
Closes #185

Fixing select default value

---

src/web/aws-cloudwatch/KinesisSetup.jsx
src/web/utils/formValidation.js

Adding pattern to Stream Name input

---

src/web/common/ValidatedInput.jsx

This fixes the lint error that snuck through into `aws` branch

Lint Error in AWS

---

src/main/java/org/graylog/integrations/aws/AWSLogMessage.java
src/main/java/org/graylog/integrations/aws/AWSMessageType.java
src/main/java/org/graylog/integrations/aws/resources/requests/CreateLogSubscriptionRequest.java
src/main/java/org/graylog/integrations/aws/service/KinesisService.java
src/main/java/org/graylog/integrations/aws/transports/KinesisPayloadDecoder.java
src/main/java/org/graylog/integrations/aws/transports/KinesisShardProcessorFactory.java
src/test/java/org/graylog/integrations/aws/codecs/AWSCodecTest.java
src/test/java/org/graylog/integrations/aws/service/AWSServiceTest.java
src/test/java/org/graylog/integrations/aws/service/KinesisServiceTest.java
src/test/java/org/graylog/integrations/aws/transports/AWSTransportTest.java
src/test/java/org/graylog/integrations/aws/transports/KinesisPayloadDecoderTest.java
src/web/aws-cloudwatch/StepHealthCheck.jsx
src/web/common/constants.js

Fixes the invalid characters that show up when raw CloudWatch logs are parsed.

Perform proper parsing for CloudWatch raw logs

---

src/web/aws-cloudwatch/KinesisStreams.jsx

This provides a little more UI around the loading of Health Check

Use common LoadingIndicator for stream Health Check

---

src/web/aws-cloudwatch/KinesisStreams.jsx
src/web/aws-cloudwatch/StepHealthCheck.jsx
src/web/aws-cloudwatch/auto-setup-steps/SetupModal.jsx
src/web/common/FormWrap.jsx
src/web/common/Permissions.jsx

- Modified location of UI components import

Use Graylog components for UI library

---

src/main/java/org/graylog/integrations/aws/transports/KinesisShardProcessorFactory.java

When a Kinesis shard is being processed and ends, it must be checkpointed. The initial release of the new AWS CloudWatch/Kinesis client did not do this as it should have. 
See relevant javadoc comment:
https://github.com/awslabs/amazon-kinesis-client/blob/98b016276b0387ed77d1049c706673ad1fbf6b22/amazon-kinesis-client/src/main/java/software/amazon/kinesis/processor/ShardRecordProcessor.java#L61
and example code:
https://docs.aws.amazon.com/streams/latest/dev/kcl2-standard-consumer-java-example.html
Fixes https://github.com/Graylog2/graylog-plugin-integrations/issues/286

Checkpoint when Kinesis shard ends

---

src/main/java/org/graylog/integrations/aws/transports/KinesisShardProcessorFactory.java

Backport: Failed to checkpoint at the end of shard

---

src/main/java/org/graylog/integrations/aws/service/KinesisService.java

3.1 Backport for issue #342 and PR #341

Backport - Retry when rate limit exception occurs for getStreams

---

package.json
pom.xml
src/main/java/org/graylog/integrations/ipfix/codecs/IpfixCodec.java
src/test/java/org/graylog/integrations/ipfix/codecs/IpfixAggregatorTest.java
src/test/java/org/graylog/integrations/ipfix/codecs/IpfixCodecTest.java

Add listfield option for custom definition files

---

src/web/aws/cloudwatch/kinesis/ExistingStreams.jsx
src/web/aws/common/Routes.js

Add documentation link

---

src/main/java/org/graylog/integrations/ipfix/inputs/IpfixUdpInput.java

Add documentation link for ipfixudpinput

---

src/main/java/org/graylog/integrations/ipfix/inputs/IpfixUdpInput.java

- pr for graylog2-server needs to be merged first. [7444](https://github.com/Graylog2/graylog2-server/pull/7444)
- Fixes issue [354]( https://github.com/Graylog2/graylog-plugin-integrations/issues/354)

fix the link to ipfix docs.

---

src/main/java/org/graylog/integrations/aws/AWSPolicyStatement.java
src/main/java/org/graylog/integrations/aws/resources/KinesisSetupResource.java
src/main/java/org/graylog/integrations/aws/resources/responses/KinesisHealthCheckResponse.java
src/main/java/org/graylog/integrations/aws/resources/responses/KinesisNewStreamResponse.java
src/main/java/org/graylog/integrations/aws/service/AWSService.java
src/main/java/org/graylog/integrations/aws/service/CloudWatchService.java
src/main/java/org/graylog/integrations/aws/service/KinesisService.java
src/main/java/org/graylog/integrations/aws/transports/KinesisConsumer.java
src/main/java/org/graylog/integrations/aws/transports/KinesisShardProcessorFactory.java
src/main/java/org/graylog/integrations/aws/transports/KinesisTransport.java

Remove extra comments

---

src/web/aws/authentication/AWSAuthenticationTypes.jsx
yarn.lock

Needed for https://github.com/Graylog2/graylog2-server/pull/7067

Updating ThemeProvider

---

src/web/aws/authentication/AWSAuthenticationTypes.jsx

Updating color variable for https://github.com/Graylog2/graylog2-server/pull/7231

Update color variable

---

pom.xml
src/test/java/org/graylog/integrations/aws/service/AWSServiceTest.java

This change updates our AWS integration to use the latest versions of AWS libraries.

Upgrading to latest versions of AWS dependencies

---

pom.xml
src/test/java/org/graylog/integrations/aws/service/AWSServiceTest.java

This is a cherry-pick merge from the `master` branch to update AWS dependencies.

Upgrade AWS Dependencies

---

src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoTCPInput.java

Change Input name. Fix [7345](https://github.com/Graylog2/graylog2-server/issues/7345) issue

Update PaloAltoTCPInput.java (fix 7345 issue)

---

src/main/java/org/graylog/integrations/IntegrationsModule.java
src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoMessageTemplate.java
src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoMessageType.java
src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xCodec.java
src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xFields.java
src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xInput.java
src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xParser.java
src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xTemplates.java
src/test/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xCodecTest.java
src/test/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xParserTest.java
src/test/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xTemplatesTest.java
src/test/python/send_syslog.py

This change adds a new Palo Alto input which supports PAN-OS v9.x schema and stores messages using the new Graylog Schema, allowing integration with Graylog Illuminate.

Merge Palo Alto plugin updates from 4.0 to 3.3

---

src/test/python/send_syslog.py

Added options limit lines sent, skip the CSV header, and add delay between lines when sending a file.

Merge log scripts

---

src/web/aws/common/hooks/useFetch.js

Backport of AWS credentials fix

---

src/web/aws/StepAuthorize.jsx
src/web/aws/authentication/AWSAuthenticationTypes.jsx
src/web/aws/authentication/AWSCustomEndpoints.jsx
src/web/aws/cloudwatch/CloudWatch.jsx
src/web/aws/cloudwatch/CloudWatchApp.jsx
src/web/aws/cloudwatch/FormAdvancedOptions.jsx
src/web/aws/cloudwatch/SidebarPermissions.jsx
src/web/aws/cloudwatch/StepHealthCheck.jsx
src/web/aws/cloudwatch/StepKinesis.jsx
src/web/aws/cloudwatch/StepReview.jsx
src/web/aws/cloudwatch/kinesis/ExistingStreams.jsx
src/web/aws/cloudwatch/kinesis/SetupNewStream.jsx
src/web/aws/cloudwatch/kinesis/setup-steps/KinesisSetupSteps.jsx
src/web/aws/cloudwatch/kinesis/setup-steps/SetupModal.jsx
src/web/aws/common/AdditionalFields.jsx
src/web/aws/common/FormWrap.jsx
src/web/aws/common/Options.jsx
src/web/aws/common/Routes.js
src/web/aws/common/SkipHealthCheck.jsx
src/web/aws/common/ValidatedInput.jsx
src/web/aws/context/AdvancedOptions.jsx
src/web/aws/context/Api.jsx
src/web/aws/context/FormData.jsx
src/web/aws/context/Steps.jsx
src/web/aws/utils/formValidation.js

This PR is reusing the link component abstraction from core, implemented in Graylog2/graylog2-server#9030.
/jenkins-pr-deps Graylog2/graylog2-server#9030

Reusing link component abstraction from core.

---

src/test/java/org/graylog/integrations/notifications/types/SlackClientTest.java

It is currently failing when run within Jenkins

Disable SlackClientTest

---

src/web/aws/cloudwatch/SidebarPermissions.jsx
src/web/aws/cloudwatch/StepHealthCheck.jsx
src/web/aws/cloudwatch/kinesis/ExistingStreams.jsx
src/web/aws/cloudwatch/kinesis/setup-steps/KinesisSetupStep.jsx
src/web/aws/common/FormWrap.jsx
src/web/aws/common/ValidatedInput.jsx

We were using obsolete icons - updated to component from Core

Use Icon component from 3.3 core

---

src/main/java/org/graylog/integrations/notifications/types/SlackClient.java
src/main/java/org/graylog/integrations/notifications/types/SlackEventNotification.java
src/main/java/org/graylog/integrations/notifications/types/SlackEventNotificationConfig.java
src/main/java/org/graylog/integrations/notifications/types/SlackEventNotificationConfigEntity.java
src/main/java/org/graylog/integrations/notifications/types/SlackMessage.java
src/test/java/org/graylog/integrations/notifications/types/SlackClientTest.java
src/test/java/org/graylog/integrations/notifications/types/SlackEventNotificationConfigTest.java
src/test/java/org/graylog/integrations/notifications/types/SlackEventNotificationTest.java
src/test/java/org/graylog/integrations/notifications/types/SlackMessageTest.java
src/web/event-notifications/event-notification-details/SlackNotificationDetails.jsx
src/web/event-notifications/event-notification-types/SlackNotificationForm.jsx
src/web/event-notifications/event-notification-types/SlackNotificationSummary.jsx

This is a backport PR for the feature #623 into 4.0 branch.

Slack Notification Plugin - add field Message Backlog Limit. (#639)

---

package.json
pom.xml

Update cloud-4.0 branch with latest changes from 4.0.
/jenkins-pr-deps Graylog2/graylog2-server#9986,Graylog2/graylog-plugin-enterprise#2023,Graylog2/graylog-plugin-enterprise-integrations#460,Graylog2/graylog-plugin-cloud#697

Sync cloud 4.0

---

src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoMessageType.java
src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xCodec.java
src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xFields.java
src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xParser.java
src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xTemplates.java
src/test/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xCodecTest.java
src/test/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xParserTest.java
src/test/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xTemplatesTest.java

This is a backport of #719 to the `4.0.3` release

Initial version of USERID parsing for Palo9x input (#719)

---

src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoCodec.java
src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoFieldTemplate.java
src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoMessageTemplate.java
src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoTypeParser.java
src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xParser.java
src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xTemplates.java

This is a backport of PR #731 to the 4.0 branch

Refactor PaloAltoTypeParser to improve performance (#731)

---

yarn.lock

Fixes: https://github.com/advisories/GHSA-r9p9-mrjm-926w

Bump elliptic to 6.5.4

---

src/main/java/org/graylog/integrations/IntegrationsModule.java
src/main/java/org/graylog/integrations/dataadapters/GreyNoiseCommunityIpLookupAdapter.java
src/test/java/org/graylog/integrations/TestWithResources.java
src/test/java/org/graylog/integrations/dataadapters/GreyNoiseCommunityIpLookupAdapterTest.java
src/test/resources/org/graylog/integrations/dataadapters/GreyNoiseCommunityIpLookupAdapter_test-parse-404.json
src/test/resources/org/graylog/integrations/dataadapters/GreyNoiseCommunityIpLookupAdapter_test-parse-LimitReached.json
src/test/resources/org/graylog/integrations/dataadapters/GreyNoiseCommunityIpLookupAdapter_test-parse-success.json
src/web/dataadapters/GreyNoiseCommunityIpLookupAdapterDocumentation.jsx
src/web/index.jsx

Backport https://github.com/Graylog2/graylog-plugin-integrations/pull/940 to the `4.2` branch.

Backport 4.2: Community greynoise iplookup adapter (#940)

---

src/main/java/org/graylog/integrations/dataadapters/GreyNoiseQuickIPDataAdapter.java

* Adds riot field to GreyNoise quickip lookup adapter
* Removes version from GreyNoise UserAgent string
* Check unsupport and invalid IPs before calling GreyNoise

Adds riot field to GreyNoise quickip lookup adapter (#951)

---

src/web/aws/common/Routes.js
src/web/event-notifications/event-notification-types/SlackNotificationForm.jsx
yarn.lock

Updating old documentation links
/jenkins-pr-deps Graylog2/graylog2-server#11874,Graylog2/graylog-plugin-enterprise#3041

Replacing outdated documentation links

---

package.json
src/web/index.jsx
src/web/webpack-entry.js
yarn.lock

Similar to Graylog2/graylog-plugin-collector#195, this PR explicitly sets the URL prefix for assets which are loaded asynchronously.

Set URL prefix for asynchronously loaded assets.

---

src/main/java/org/graylog/integrations/IntegrationsModule.java
src/main/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsEventNotification.java
src/main/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsEventNotificationConfig.java
src/main/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsEventNotificationConfigEntity.java
src/main/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsMessage.java
src/main/java/org/graylog/integrations/notifications/types/util/RequestClient.java
src/test/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsEventNotificationConfigTest.java
src/test/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsEventNotificationTest.java
src/test/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsMessageTest.java
src/web/event-notifications/event-notification-details/TeamsNotificationDetails.tsx
src/web/event-notifications/event-notification-types/TeamsNotificationForm.tsx
src/web/event-notifications/event-notification-types/TeamsNotificationSummary.tsx
src/web/event-notifications/types.ts
src/web/index.jsx
tsconfig.json

Microsoft Teams Notification
Co-authored-by: S srinidhi <ssrinidhi@Ss-MacBook-Pro.local>
Co-authored-by: Dan Torrey <dan@graylog.com>
backport of #1064

Microsoft Teams Notification (#1064)

---

src/web/aws/cloudwatch/CloudWatch.test.jsx
src/web/aws/cloudwatch/StepReview.test.jsx

Please have a look at https://github.com/Graylog2/graylog2-server/pull/13285 for more information.

Remove no longer needed `CurrentUserStore` mocks.

---

src/main/java/org/graylog/integrations/IntegrationsModule.java
src/main/java/org/graylog/integrations/migrations/V20220622071600_MigratePagerDutyV1.java

Migrate PagerDuty Notifications from v1 to v2 (#1077)

---

changelog/unreleased/issue-1054.toml
changelog/unreleased/issue-1096.toml

Let's collect all 5.0 changelog snippets in this pull request.
Please add your snippet files to the `changelog/unreleased` folder
as described in our internal documentation.
Thank you!

Add 5.0 Changelogs

---

src/main/java/org/graylog/integrations/aws/service/AWSService.java
src/main/java/org/graylog/integrations/notifications/types/SlackEventNotification.java
src/main/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsEventNotification.java
src/main/java/org/graylog/integrations/pagerduty/PagerDutyNotification.java
src/test/java/org/graylog/integrations/aws/service/AWSServiceTest.java
src/test/java/org/graylog/integrations/notifications/types/SlackEventNotificationTest.java
src/test/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsEventNotificationTest.java
src/test/java/org/graylog/integrations/pagerduty/PagerDutyNotificationTest.java

/nocl
/jenkins-pr-deps Graylog2/graylog2-server#14222,Graylog2/graylog-plugin-enterprise#4470,Graylog2/graylog-plugin-enterprise-integrations#957

Refactor NodeId class and all usages

---

src/web/aws/authentication/AWSAuthenticationTypes.jsx

fix Kinesis on-screen validation for automatic authentication type

---

package.json

Run Jest with --maxWorkers=50% flag

---

changelog/unreleased/pr-1348.toml
src/main/java/org/graylog/integrations/notifications/types/SlackEventNotification.java
src/main/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsEventNotification.java
src/test/java/org/graylog/integrations/notifications/types/SlackEventNotificationTest.java
src/test/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsEventNotificationTest.java
src/web/event-notifications/event-notification-types/SlackNotificationForm.tsx
src/web/event-notifications/event-notification-types/TeamsNotificationForm.tsx

With this PR we are including a "Alert Replay" link in the template for slack and teams notifications.
Related to https://github.com/Graylog2/graylog2-server/pull/15922

Include link to replay an alert in teams and slack notification template.
