- src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoParser.java
- src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoTCPInput.java
- src/test/java/org.graylog.integrations/inputs/paloalto/PaloAltoCodecTest.java
* Use Syslog TCP transport to correctly handle frame length
* Fully migrate to Syslog TCP Transport
* Trim line breaks from the message before parsing
* Add tests
* Roll back log message
Fixes #10
(cherry picked from commit d99cdc2f32ec4dc27c63e240d7ef5929b6dbd0e3)
> Fix Palo Alto input parsing issue (#11)

- src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoParser.java
- src/test/java/org.graylog.integrations/inputs/paloalto/PaloAltoCodecTest.java
Use an actual CSV parser to parse the PA payload instead of just straight splitting on commas.
This causes quoted CSV values with embedded commas to be parsed correctly as a single value. eg. \"Testing 1, 2, 3\" will now be correctly parsed as a single value.
Fixes #15
Needs backport to 3.0 branch for 3.0.2 release.
> Use actual CSV parser to correctly handle quoted values

- README.md
This PR removes duplicate and outdated details from the Integrations repo readme. Most of the details are present in the official docs http://docs.graylog.org/en/3.0/pages/integrations.html, so I thought it made sense to just refer the user to them and not duplicate the details here in this readme.
> Update Integrations repo readme

- src/main/java/org/graylog/integrations/aws/CloudWatchService.java
- src/main/java/org/graylog/integrations/aws/KinesisService.java
- src/main/java/org/graylog/integrations/aws/Main.java
- src/main/java/org/graylog/integrations/aws/resources/AWSResource.java
- src/main/java/org/graylog/integrations/aws/service/AWSService.java
- src/test/java/org.graylog.integrations/aws/KinesisServiceTest.java
> Add getRegion into AWSResource

- src/main/java/org/graylog/integrations/aws/KinesisService.java
- src/main/java/org/graylog/integrations/aws/resources/responses/KinesisHealthCheckResponse.java
- src/main/java/org/graylog/integrations/aws/resources/responses/RegionResponse.java
Kinesis cleanup:
- Remove unneeded method
- Increase max # of Kinesis pages that can be pulled from 100 to 1000. This is a max limit to prevent potential infinite loop.
- Use underscore_case instead of cammelCase for JSON properties. Generally in Graylog we use underscores.
> Kinesis-related code cleanup

- src/main/java/org/graylog/integrations/aws/resources/AWSResource.java
- src/main/java/org/graylog/integrations/aws/resources/responses/AvailableAWSService.java
- src/main/java/org/graylog/integrations/aws/resources/responses/AvailableAWSServiceSummmary.java
- src/main/java/org/graylog/integrations/aws/service/AWSService.java
- src/test/java/org.graylog.integrations/aws/AWSServiceTest.java
Add API call that returns a list of available services for the Choose from Available Services page. 
To test this out, this CURL command can be used: `curl http://someuser:somepass@localhost:9000/api/plugins/org.graylog.integrations/aws/availableServices`
Resolves #50
> Add Available Services API call

- src/main/java/org/graylog/integrations/aws/resources/AWSResource.java
- src/main/java/org/graylog/integrations/aws/resources/requests/AWSRequestImpl.java
- src/main/java/org/graylog/integrations/aws/resources/responses/AWSRegion.java
- src/main/java/org/graylog/integrations/aws/resources/responses/AvailableService.java
- src/main/java/org/graylog/integrations/aws/resources/responses/AvailableServiceResponse.java
- src/main/java/org/graylog/integrations/aws/resources/responses/HealthCheckResponse.java
- src/main/java/org/graylog/integrations/aws/resources/responses/LogGroupsResponse.java
- src/main/java/org/graylog/integrations/aws/resources/responses/RegionsResponse.java
- src/main/java/org/graylog/integrations/aws/resources/responses/StreamsResponse.java
- src/main/java/org/graylog/integrations/aws/service/AWSService.java
- src/main/java/org/graylog/integrations/aws/service/CloudWatchService.java
- src/main/java/org/graylog/integrations/aws/service/KinesisService.java
- src/test/java/org.graylog.integrations/aws/cloudwatch/CloudWatchServiceTest.java
- src/test/java/org.graylog.integrations/aws/service/AWSServiceTest.java
- src/test/java/org.graylog.integrations/aws/service/KinesisServiceTest.java
The `AWSResource.getLogGroupNames` and `AWSResource.getKinesisStreams` API resource methods now require a POST body with region and AWS credentials. Before, these methods were using implicit environment variable credentials.
> Pass region and AWS credentials with AWS API requests

- src/main/java/org/graylog/integrations/aws/AWSMessageType.java
- src/main/java/org/graylog/integrations/aws/resources/AWSResource.java
- src/main/java/org/graylog/integrations/aws/resources/responses/HealthCheckResponse.java
- src/main/java/org/graylog/integrations/aws/resources/responses/KinesisHealthCheckResponse.java
- src/main/java/org/graylog/integrations/aws/service/KinesisService.java
- src/test/java/org.graylog.integrations/aws/service/KinesisServiceTest.java
This changes the Health Check response to return a list of message fields instead of the text summary. Resolves #109
New example response:
```
{
"success": true,
"input_type": "KINESIS_FLOW_LOGS",
"explanation": "Success. The message is a Flow Log message.",
"message_fields": {
"protocol_number": 6,
"src_addr": "172.1.1.2",
"source": "aws-flowlogs",
"message": "eni-3244234 ACCEPT TCP 172.1.1.2:80 -> 172.1.1.2:2264",
"dst_addr": "172.1.1.2",
"dst_port": 2264,
"action": "ACCEPT",
"_id": "4ecfcb60-9913-11e9-a3a6-32ca2bdd4771",
"aws_log_stream": "eni-3423-all",
"timestamp": "2019-06-05T12:35:44.000Z"
}
}
```
The plan is to display these fields in a formatted way in the UI instead of in a big block of text.
> Return JSON message field list in response from Health Check

- src/main/java/org/graylog/integrations/aws/resources/AWSResource.java
No need for this docs duplication. The System > Nodes > API Browser already documents them.
> Removed unneeded inline cURL API documentation

- src/main/java/org/graylog/integrations/aws/resources/requests/AWSInputCreateRequest.java
- src/main/java/org/graylog/integrations/aws/service/AWSService.java
Use these standard key/secret field names for AWS key and secret for the Save Input AWS endpoint (From the AWSRequest interface). All other AWS API requests should be using these already.
`aws_access_key_id` (previously `aws_access_key`)
`aws_secret_access_key` (previously `aws_secret_key`)
The region field was also changed to use the central `AWSRequest` constant.
> Use standard field names for AWS key and secret

- src/web/aws-cloudwatch/KinesisSetup.jsx
- src/web/aws-cloudwatch/KinesisStreams.jsx
- src/web/aws-cloudwatch/StepAuthorize.jsx
- src/web/aws-cloudwatch/StepHealthCheck.jsx
- src/web/aws-cloudwatch/StepReview.jsx
- src/web/aws-cloudwatch/context/default_settings.js
- src/web/aws-cloudwatch/hooks/useFetch.js
- src/web/common/FormWrap.jsx
- src/web/common/ValidatedInput.jsx
- src/web/utils/formValidation.js
This moves the disabling of the submit button from being in the FormWrap to being a prop so that each FormWrap can be controlled instead of expecting the component to know how we're validating fields.
This also updates the styling a little bit for the Field validation notice 
Lastly, it moves the form's title and description to props on FormWrap, named `title` and `description` respectively. This way the layout will stay consistent as we begin integrating error messages that will be output to the UI.
This PR is a precursor to getting #146 ready to merge in as this will be creating the rendered errors.
> Form Field Error Handling

- src/main/java/org/graylog/integrations/aws/resources/KinesisSetupResource.java
Creates a record of when users agree to create AWS resources through the AWS Kinesis auto-setup flow. 
Since AWS resources cost money, we are explicitly recording when a particular user agrees to create resources though the Kinesis auto-setup flow.
Only the user id is logged (instead of the full user name) to avoid leaking user names/full names out into the server log file.
The resulting message looks like this (note that the local admin user name is logged since it does not actually exist in the database):
>  User [local:admin] agreed to the Kinesis auto-setup, which will create a Kinesis stream [test], role/policy, and a CloudWatch log group Subscription. This has been recorded, since AWS resources that will cost money are being created at the sole request of this user.
> Record when users agree to auto-setup

- src/main/java/org/graylog/integrations/aws/resources/AWSResource.java
- src/main/java/org/graylog/integrations/aws/resources/KinesisSetupResource.java
- src/main/java/org/graylog/integrations/aws/resources/responses/KinesisPermissionsResponse.java
- src/main/java/org/graylog/integrations/aws/service/AWSService.java
- src/test/java/org/graylog/integrations/aws/resources/KinesisSetupResourceTest.java
- src/test/java/org/graylog/integrations/aws/service/AWSServiceTest.java
Adds an API request to get the permission policy for the regular setup flow, and for the auto-setup flow.
Closes #174
> Add API request to get permissions

- src/main/java/org/graylog/integrations/aws/resources/KinesisSetupResource.java
- src/test/java/org/graylog/integrations/aws/resources/KinesisSetupResourceTest.java
Remove the mocked responses for the Kinesis auto-setup flow. These were previously added to make it easer to test the auto-setup UI. They are no longer needed.
> Remove auto-setup mocking

- src/main/java/org/graylog/integrations/IntegrationsModule.java
- src/main/java/org/graylog/integrations/audit/IntegrationsAuditEventTypes.java
- src/main/java/org/graylog/integrations/aws/resources/AWSResource.java
- src/main/java/org/graylog/integrations/aws/resources/KinesisSetupResource.java
- src/main/java/org/graylog/integrations/aws/resources/responses/CreateRolePermissionResponse.java
- src/main/java/org/graylog/integrations/aws/service/KinesisService.java
Add Enterprise Audit Log entries for the following AWS actions:
* Create a new AWS input through the new AWS setup flow.
* Performing the automated Kinesis setup, which includes: Kinesis stream creation, IAM role creation, and CloudWatch -> Kinesis subscription creation.
These actions both create resources in the customer's AWS and Graylog environments, so I think we want to create Audit Log entries for them.
See https://github.com/Graylog2/graylog-plugin-enterprise/pull/1199 for the respective Audit Log formats.
> Add Audit Log entries for AWS Kinesis/CloudWatch

- pom.xml
Explicitly include only the packages that are needed in the shaded artifact. This prevents the entire SDK from being packaged and distributed with this plugin (~150MB).
> Reduce the shaded AWS SDK bundle size

- GETTING-STARTED.md
- README.md
Prefer HTTPS over HTTP and link to the latest available documentation.
> Tweaks to documentation links

- package.json
- yarn.lock
`styled-components` now available via `graylog-web-plugin` from core https://github.com/Graylog2/graylog2-server/blob/master/graylog2-web-interface/packages/graylog-web-plugin/package.json#L53-L54
> Remove styled-components in favor of graylog-web-plugin

- src/main/java/org/graylog/integrations/audit/IntegrationsAuditEventTypes.java
Fix #297 by adding missing audit log registration. 
I tested and confirmed that the error indicated in the issue is no longer occurring at server startup and that the specific audit log entry is generating.
> Add missing audit registration

- src/main/java/org/graylog/integrations/aws/service/KinesisService.java
Fixes #341 
* Retries if Kinesis `LimitExceededException` occurs.
* Increases page size for streams from 30 to 400 to reduce the need for successive calls. Retrying successive requests will only be needed for extremely large numbers of streams.
**Ref :** 
https://docs.aws.amazon.com/streams/latest/dev/fundamental-stream.html
https://docs.amazonaws.cn/en_us/kinesis/latest/APIReference/kinesis-api.pdf
https://docs.aws.amazon.com/cli/latest/reference/kinesis/create-stream.html
**CLI Reference Guide:**
https://docs.aws.amazon.com/cli/latest/reference/kinesis/describe-limits.html
**CLI-Example  for AWS services IAM(Dynamodb|Cloud Watch|Kinesis...):**
````
helium@helium-Precision-5540:~/workspace/config/shell$ aws iam get-user
{
"User": {
"UserName": "xxxx", 
"PasswordLastUsed": …
```
> Retry when rate limit exception occurs for getStreams

- src/main/java/org/graylog/integrations/aws/AWSAuthFactory.java
- src/main/java/org/graylog/integrations/aws/AWSClientBuilderUtil.java
- src/main/java/org/graylog/integrations/aws/transports/KinesisConsumer.java
- src/test/java/org/graylog/integrations/aws/AWSAuthFactoryTest.java
Correctly return an `AwsCredentialsProvider` without overriding or calling the `resolveAuthentication` method. This method should only be called internally within the AWS SDK. 
Previously, the Graylog `AWSAuthProvider` implementation  both manually called the `resolveAuthentication` method, an overrode it, which resulted in token refresh requests from [StsAssumeRoleCredentialsProvider](https://sdk.amazonaws.com/java/api/2.0.0-preview-11/software/amazon/awssdk/services/sts/auth/StsAssumeRoleCredentialsProvider.html) to be ignored.
Now, the implementation of [AWSAuthFactory](https://github.com/Graylog2/graylog-plugin-integrations/pull/389/files#diff-8521348d7b37ad0ba737860db3154682) simply creates and returns the `AwsCredentialsProvider`, which allows it to internally handle all credential …
> Correctly return an unresolved authentication provider

- src/main/java/org/graylog/integrations/aws/AWSAuthFactory.java
- src/test/java/org/graylog/integrations/aws/AWSAuthFactoryTest.java
The argument order for `AWSAuthFactory.create` was wrong in #389, which causes key and secret authentication to fail. My test of this obviously was not correct, because this breaks key/secret auth :D Sorry about that. I added a basic unit test was added that would catch the argument transposition error in the future.
When reviewing, please check, the callers of `AWSAuthFactory.create` and make sure the argument order is correct.
> Fix incorrect `AWSAuthFactory.create` argument order

- src/main/java/org/graylog/integrations/aws/AWSAuthFactory.java
- src/main/java/org/graylog/integrations/aws/AWSClientBuilderUtil.java
- src/main/java/org/graylog/integrations/aws/transports/KinesisConsumer.java
- src/test/java/org/graylog/integrations/aws/AWSAuthFactoryTest.java
Backport of #389 and #392 
Cherry-picked commit 730302ddc2d3f3db2f2dd70910453ebceb85c115 3edaba46c911de86b0cc6f1fc06693821d66db18 and based this branch off of the latest `3.2` branch.
> Backport: Correctly return an unresolved authentication provider (#389)

- jenkins.groovy
Add logic for a Jenkins pipeline. Merging this PR will enable the CI job on the new Jenkins instance at http://jenkins.ci.torch.sh.
I will leave the old Jenkins build enabled this week so builds can be compared between the two environments. Once we are sure the builds succeed or fail in the same way in both environments, I will disable the build in the old environment and complete migration.
> Add jenkins pipeline

- src/main/java/org/graylog/integrations/aws/AWSClientBuilderUtil.java
- src/main/java/org/graylog/integrations/aws/service/AWSService.java
- src/test/java/org/graylog/integrations/aws/AwsClientBuilderUtilTest.java
The AWS Input was not working for GovCloud regions due to hard-coded region value when constructing the IAM client.  Additionally, the recommended policy was missing a permission that is more strictly enfoced on GovCloud.  This updates IAM client construction to work for GovCloud and adds the missing permission to the recommended policy.
Tested locally with GovCloud Access Key and Secret.
> Updates to fix AWS Input for GovCloud

- src/main/java/org/graylog/integrations/aws/AWSClientBuilderUtil.java
- src/main/java/org/graylog/integrations/aws/service/AWSService.java
- src/test/java/org/graylog/integrations/aws/AwsClientBuilderUtilTest.java
Cherry-picked the commit for the GovCloud fix.  This change ensures that IAM client is constructed correctly for users setting up the Kinesis/Cloudwatch input to pull data from GovCloud.
> GovCloud Fix

- src/test/python/send_syslog.py
In order to test Syslog-based plugins, we need the ability to generate traffic. For plugins like Palo Alto, where the traffic comes from a proprietary device, that can be quite difficult.  This script will send Syslog TCP/UDP messages with arbitrary payloads to a specified server/port, which allows us to take the payloads of real Palo logs and replay them as if they were coming from an actual Palo Alto device.
https://github.com/Graylog2/graylog-plugin-integrations/issues/483
Script usage:
Standard Syslog TCP single message:
Standard Syslog TCP input file:
Palo Alto:
> Add a test script to send Syslog TCP/UDP messages to Graylog.

- pom.xml
We build OS packages outside of maven.
> Remove DEB and RPM packaging build

- src/main/java/org/graylog/integrations/IntegrationsModule.java
- src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoMessageTemplate.java
- src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoMessageType.java
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xCodec.java
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xFields.java
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xInput.java
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xParser.java
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xTemplates.java
- src/test/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xCodecTest.java
- src/test/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xParserTest.java
- src/test/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xTemplatesTest.java
- src/test/python/send_syslog.py
The Palo Alto v9x plugin is built on the existing code for Palo v8.  This new plugin handles the PAN-OS v9.x schema and adds four new message types.  However, it no longer supports user-defined schemas.  Instead, it parses messages into the new Graylog Schema.
Changes have been tested with JUnits and by pushing a variety of PAN-OS 9.x messages into a local Graylog instance.
There are still some changes that need to be made in the templates, as noted by the TODO comments.
> Add initial version of Palo Alto v9x plugin

- src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoMessageType.java
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xCodec.java
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xParser.java
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xTemplates.java
- src/test/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xCodecTest.java
- src/test/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xParserTest.java
Palo Alto Networks updated the template for GlobalProtect logs in version 9.1.3 in such a way that Graylog is no longer able to successfully parse them.  This change adds support for v9.1.3+ GlobalProtect messages while maintaining support for v9.0-9.1.2 GlobalProtect messages.
Relevant details on the difference between 9.0-9.1.2 and 9.3 GlobalProtect logs can be found in the linked issue.
Because we do not have access to a Palo Alto device or a source for 9.1.3 logs, the only validation done has been with JUnit tests to ensure PAN GlobalProtect logs are parsed with the correct template.
> Update Palo 9.x to handle 9.1.3 GlobalProtect logs - Fixes #540

- src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoMessageType.java
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xCodec.java
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xParser.java
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xTemplates.java
- src/test/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xCodecTest.java
- src/test/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xParserTest.java
Merge Palo Alto 9x plugin changes to 3.3 branch
> Update Palo 9.x to handle 9.1.3 GlobalProtect logs - Fixes #540 (#541)

- src/web/aws/common/hooks/useFetch.js
`Key & Secret` were not being properly used during authentication, it was only trying to use the `Authomatic` authentication method of on-disk files.
This PR resolves the issue by placing a conditional within the fetch options.
> AWS CloudWatch Authentication Key & Secret Fix

- src/web/aws/cloudwatch/CloudWatchApp.jsx
This PR is reusing the `withParams` HOC supplied in core.
> Reuse `withParams` abstraction from core.

- src/test/java/org/graylog/integrations/notifications/types/SlackClientTest.java
- SlackClientTest uses `mock` httpClient and the imports have been optimized.
> Using mock okhttpclient 

- src/main/java/org/graylog/integrations/notifications/types/SlackEventNotification.java
Applied the fix for `InconsistentCapitalization`
**Description** 
`
[WARNING] /home/priya/workspace/graylog/master/graylog-project-repos/graylog-plugin-integrations/src/main/java/org/graylog/integrations/notifications/types/SlackEventNotification.java:[70,94] [InconsistentCapitalization] Found the field 'slackClient' with the same name as the parameter 'slackCLient' but with different capitalization.
(see http://errorprone.info/bugpattern/InconsistentCapitalization)
`
> slack - fix InconsistentCapitalization

- src/web/index.jsx
- src/web/pager-duty/PagerDutyNotificationDetails.jsx
We discovered in smd-dev that PagerDuty notifications did not have a Details page.  This PR adds the Details page.
Tested locally:
Verified locally with `yarn lint` that no eslint errors exist.
> Add Details page for PagerDuty Notifications

- src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoTypeParser.java
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xFields.java
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xInput.java
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xTemplates.java
- src/test/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xTemplatesTest.java
Palo Alto Networks has released the schemas for PAN-OS 10.  This change updates the Palo Alto 9.x input to support the PAN-OS 10 schemas and also makes some other requested field changes.  One additional change in this PR is that when multiple instances of the same key are used to build a Palo Alto message, the message field will be converted to a list of all unique values.
The changes to existing fields and list conversion behavior were tested with JUnit tests.  No test data is available to test the PAN-OS 10 schema changes.
> Palo Alto input updates to support PANOS v10 schemas

- src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoTypeParser.java
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xFields.java
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xInput.java
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xTemplates.java
- src/test/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xTemplatesTest.java
This PR is a backport of PR #658 (Palo Alto input support for PAN-OS v10 templates) to the `4.0` branch.  See original PR for details.
> Backport #658 to 4.0.1

- src/main/java/org/graylog/integrations/notifications/types/SlackEventNotificationConfig.java
- src/test/java/org/graylog/integrations/notifications/types/SlackEventNotificationConfigTest.java
Per [Discord documentation](https://birdie0.github.io/discord-webhooks-guide/other/slack_formatting.html), Discord webhooks support messages in Slack format.  However, due to the current webhook URL validation, customers cannot use the Slack Notification plugin to send messages to Discord.  This change updates the webhook validation pattern to also accept properly formatted Discord webhook URLs.
Added JUnit test case to verify validation passes for Discord webhooks.
Validated on Discord
> Update Slack plugin to allow Discord webhooks

- src/main/java/org/graylog/integrations/notifications/types/SlackEventNotificationConfig.java
- src/test/java/org/graylog/integrations/notifications/types/SlackEventNotificationConfigTest.java
This is a backport of #661 to the `4.0` branch for the `4.0.1` bugfix release.
Previously, the Slack notification plugin only allowed webhook URLs for Slack.  However, Discord also allows Slack-formatted messages to be sent to its own webhook URLs.  In order to increase the usefulness of the Slack notification plugin, this change updates the webhook validation to allow both Slack and Discord webhook URLs.
> Merge Slack-Discord update to 4.0.1

- src/main/java/org/graylog/integrations/IntegrationsModule.java
Do not register Cloudwatch input on cloud environments, since that is not supported yet.
Fixes Graylog2/graylog-plugin-cloud#619
/jenkins-pr-deps Graylog2/graylog2-server#9808
> Disable Cloudwatch on cloud

- src/main/java/org/graylog/integrations/IntegrationsModule.java
Forwarder was failing to start with current Guice config because it included Notifications that depend on services not present in the Forwarder.  This change splits the Guice config into `server` and `universal` sections and moves the Notifications into the `server` section.
Verified that the Forwarder successfully starts with the modified config.
> Update Guice config to split server-only and universal

- src/main/java/org/graylog/integrations/IntegrationsModule.java
Backport #686 into `cloud-4.0` so that it can be used with the current Cloud code.
I suppose there is no need to also backport into `4.0`, since this is only needed for the Forwarder, which. is only used with `cloud-4.0`
> Backport: Update Guice config to split forwarder and server (#686)

- src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoMessageType.java
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xCodec.java
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xFields.java
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xParser.java
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xTemplates.java
- src/test/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xCodecTest.java
- src/test/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xParserTest.java
- src/test/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xTemplatesTest.java
This change adds support for the `USERID` log type in the Palo Alto 9.x input.  This is needed for upcoming work on Graylog Illuminate.
JUnit tests have been added to ensure the new message type is handled as expected.
Note: there is currently an open question regarding the `User Group Flags` (position 32) and `User by Source` (position 32) fields in the `USERID` log type.  Per the Palo schema, positions 30 and 31 should be reserved for future use.  However, test logs obtained both from SumoLogic and from Nick's own Palo firewall seem to show `User Group Flags` in position 30 and `User by Source` in position 31.  We need to resolve this discrepancy before releasing this update.
> Initial version of USERID parsing for Palo9x input

- src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoCodec.java
- src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoFieldTemplate.java
- src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoMessageTemplate.java
- src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoTypeParser.java
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xParser.java
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xTemplates.java
As documented in #726, a customer reported perfomrance issues with the Palo 9.x input.  
This change is an attempt to improve Palo input parse times by ensuring the Palo template fields are ordered by position and iterating over the input string from beginning to end rather than going through the unordered template fields and essentially doing random access on the input string.
Verified that the changes do not break existing Palo JUnits.  Also tested locally with the data driver script and sample Palo log files.
> Refactor PaloAltoTypeParser to improve performance

- babel.config.js
- jest.config.js
- package.json
- pom.xml
- src/main/java/org/graylog/integrations/IntegrationsModule.java
- src/test/web/aws/FormData.fixtures.js
- src/test/web/fileMock.js
- src/web/aws/authentication/AWSAuthenticationTypes.jsx
- src/web/aws/authentication/Automatic.jsx
- src/web/aws/cloudwatch/CloudWatch.jsx
- src/web/aws/cloudwatch/CloudWatch.test.jsx
- src/web/aws/cloudwatch/CloudWatchApp.jsx
- src/web/aws/cloudwatch/EmbeddedCloudWatchApp.jsx
- src/web/aws/cloudwatch/StepReview.jsx
- src/web/aws/cloudwatch/StepReview.test.jsx
- src/web/aws/common/Routes.js
- src/web/aws/common/formDataAdapter.js
- src/web/aws/common/formDataAdapter.test.js
- src/web/aws/common/hooks/useFetch.js
- src/web/index.jsx
- yarn.lock
This PR adapts the existing AWS custom Input UI for the Forwarder. The main changes consist in:
- Making it possible to render the UI embedded into another page, instead of using a separate page for it
- Bypass the Input submission through the plugin API, and instead let the Forwarder create the Input itself. The regular Input creation will still work as it did before
- Add frontend tests and configure them in the project
- Fix some smaller linter issues
Needs https://github.com/Graylog2/graylog-plugin-cloud/pull/741 for the forwarder input UI to work.
/jenkins-pr-deps Graylog2/graylog2-server#10072,Graylog2/graylog-plugin-cloud#741
> Support AWS custom Input UI in Forwarder

- package.json
- pom.xml
Update `cloud-4.0` with the latest `4.0` changes.
/jenkins-pr-deps Graylog2/graylog2-server#10406,Graylog2/graylog-plugin-enterprise#2185,Graylog2/graylog-plugin-enterprise-integrations#531,Graylog2/graylog-plugin-cloud#844
> Sync cloud 4.0

- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xCodec.java
- src/test/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xTemplatesTest.java
Per issue #816, customers have noticed issues with the `timestamp` field in PAN 9.x inputs.  This change ensures that the `timestamp` field gets converted from `String` to `DateTime` in the codec.
This has been tested locally with JUnit tests.
> Ensure PAN timestamps are DateTime not String (#816)

- src/main/java/org/graylog/integrations/notifications/types/SlackEventNotificationConfig.java
- src/test/java/org/graylog/integrations/notifications/types/SlackEventNotificationConfigTest.java
Per #835, the Slack Notification plugin is currently only allowing Slack and Discord webhook URLs when there are other messaging systems capable of accepting Slack-formatted input.  This change updates the Slack Notification plugin to do basic URL validation on provided webhook URLs unless those URLs include "slack" or "discord" in the domain name.  Webhook URLs with "slack" or "discord" in the domain name, will be further validated against the existing Slack/Discord patterns.
JUnit test has been updated to cover all new cases.
> Only validate Slack Notif webhook URL if it is a Slack or Discord URL

- package.json
- yarn.lock
This PR is assisting Graylog2/graylog2-server#10900 to apply the required changes in the enterprise repo for Jest v27.
/jenkins-pr-deps Graylog2/graylog2-server#10900,Graylog2/graylog-plugin-enterprise#2429,Graylog2/graylog-plugin-enterprise-integrations#587
> Updating to Jest v27.

- src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoFieldType.java
- src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoTypeParser.java
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xCodec.java
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xTemplates.java
This moves the timestamp parsing to an earlier stage in the processing,
and avoids setting an intermediate String to a Message timestamp field.
The changes introduced in
https://github.com/Graylog2/graylog2-server/pull/11149
are replacing unparseable timestamps with the current time.
Thus the previous approach of fixTimestampField() will not
find the earlier set String timestamp anymore.
Refs https://github.com/Graylog2/graylog-plugin-integrations/pull/825
> Parse timestamps in PaloAltoTypeParser

- src/main/java/org/graylog/integrations/IntegrationsModule.java
- src/main/java/org/graylog/integrations/dataadapters/GreyNoiseQuickIPDataAdapter.java
- src/test/java/org/graylog/integrations/dataadapters/GreyNoiseDataAdapterTest.java
- src/web/dataadapters/GreyNoiseAdapterDocumentation.jsx
- src/web/index.jsx
- Renames GreyNoise Data Adapter to GreyNoise Quick IP Lookup 
- Adds generic "Graylog/Version" User-Agent header to GreyNoise API call - open to suggestions on what else to add to that header
> Renames OS GreyNoise adapter and adds User-Agent header

- pom.xml
- src/test/java/org/graylog/integrations/aws/service/AWSServiceTest.java
This fixes #722 by upgrading the aws-java-sdk to the newest version.
For others, remember to set the following in helm chart to allow the aws-java-sdk to read the token file (from `AWS_WEB_IDENTITY_TOKEN_FILE`):
```
graylog:
podSecurityContext:
fsGroup: 1100
```
> Upgrade aws-java-sdk to fix IRSA on EKS

- src/main/java/org/graylog/integrations/IntegrationsModule.java
- src/main/java/org/graylog/integrations/dataadapters/GreyNoiseQuickIPDataAdapter.java
- src/test/java/org/graylog/integrations/dataadapters/GreyNoiseDataAdapterTest.java
- src/web/dataadapters/GreyNoiseAdapterDocumentation.jsx
- src/web/index.jsx
Backport of #939 to 4.2
Relates to Graylog2/graylog-plugin-enterprise#2885
> Renames OS GreyNoise adapter and adds User-Agent header (#939)

- src/main/java/org/graylog/integrations/dataadapters/GreyNoiseCommunityIpLookupAdapter.java
- src/main/java/org/graylog/integrations/dataadapters/GreyNoiseQuickIPDataAdapter.java
* adds missing riot field to response
* removes graylog version from user agent string
> Adds riot field to GreyNoise quickip lookup adapter

- src/main/java/org/graylog/integrations/notifications/types/SlackClient.java
- src/test/java/org/graylog/integrations/notifications/types/SlackClientTest.java
The Slack API is issuing 302 redirects for unknown
webhook URLs. The eventual target will return a 200,
so the http client will treat them as successful
By turning off redirects for slack notifications, we
can detect these cases as failures.
Fixes https://github.com/Graylog2/graylog2-server/issues/12315
> Don't follow redirects when calling Slack API

- jest.config.js
- package.json
- yarn.lock
This is a companion PR for Graylog2/graylog2-server#12562, doing the required adjustments in order to support the upgrade to jest v28.
/jenkins-pr-deps Graylog2/graylog2-server#12562
> Preparing upgrade to jest v28.

- src/main/java/org/graylog/integrations/IntegrationsModule.java
Properly registers event notification Jackson subtype for Pager Duty, Slack, and Teams Notifications. Prevents the following exception when attempting to install Event Notification content packs:
```
java.lang.IllegalArgumentException: Could not resolve type id '<notification-type>' as a subtype of...
```
Closes https://github.com/Graylog2/graylog2-server/issues/7801 https://github.com/Graylog2/graylog-plugin-integrations/issues/1113
/jenkins-pr-deps https://github.com/Graylog2/graylog2-server/pull/13171
> Properly register notification config entity subtypes

- src/main/java/org/graylog/integrations/IntegrationsModule.java
Backport https://github.com/Graylog2/graylog-plugin-integrations/pull/1129 to the `4.3` branch.
/jenkins-pr-deps https://github.com/Graylog2/graylog2-server/pull/13197
> Backport: Properly register notification config entity subtypes

- src/main/java/org/graylog/integrations/IntegrationsModule.java
- src/main/java/org/graylog/integrations/migrations/V20220622071600_MigratePagerDutyV1.java
Updates the `type.config` field for PagerDuty notifications.
closes #1054
> Migrate PagerDuty Notifications from v1 to v2

- src/main/java/org/graylog/integrations/IntegrationsModule.java
As you can see on the comment on top of configureUniversalBindings(), the forwarder does not have MongoDB.
Refs #1163
> Don't add migrations to the forwarder bindings

- src/web/aws/cloudwatch/StepReview.jsx
With this PR we are removing not needed `line-height`s.
Related to https://github.com/Graylog2/graylog2-server/pull/13530.
> Remove not needed usage of CSS `line-height`.

- src/main/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsEventNotification.java
- src/main/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsMessage.java
- src/test/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsEventNotificationTest.java
- src/web/event-notifications/event-notification-types/TeamsNotificationForm.tsx
Previously, the actual format of the MS Teams Notification template didn't matter all that much. The code was parsing each line into a key value pair with a colon char delimiter so the `sections.facts` part of the [O365 connector card](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#properties-of-the-office-365-connector-card), which relies on key-value pairings, could be used. If the value itself contained a colon then it would be cut off from that colon on. This broke timestamp fields and just didn't work all that well for things like backlog messages, which doesn't fit into a key-value pattern. 
These changes instead use the `text` field of the O365 connector card which allows for the template of the notification to include HTML or …
> Rework Microsoft Teams Notification Templating

- changelog/unreleased/pr-1291.toml
- src/main/java/org/graylog/integrations/aws/transports/KinesisTransport.java
Replaces all representations in strings for inputs to a new toIdentifier() method which concatenates {name}/{title}/{id}
/jenkins-pr-deps Graylog2/graylog2-server#14562
to be merged after / dependent on https://github.com/Graylog2/graylog2-server/pull/14562
> feat: consistent identifier for inputs

- src/web/aws/AWSInputConfiguration.jsx
- src/web/aws/cloudwatch/CloudWatch.jsx
- src/web/aws/cloudwatch/CloudWatch.test.jsx
This PR is supporting Graylog2/graylog2-server#12911 in migrating to `react-router` v6.
> Updating to `react-router` v6.

- changelog/unreleased/issue-1327.toml
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xTemplates.java
Closes #1327 
Closes Graylog2/graylog2-server#14363
Relevant links for justification of changes:
[PAN Docs](https://docs.paloaltonetworks.com/pan-os/11-0/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/globalprotect-log-fields) show correct log format
[PAN KB Article](https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA10g000000ClSsCAK) shows priority integer values are related to a priority string value that seems to be being used in log messages
> Fix field parsing for Global Protect 9.1.3 template

- changelog/unreleased/issue-1327.toml
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xTemplates.java
> 5.0 Backport: Fix field parsing for Global Protect 9.1.3 template (#1328)

- changelog/unreleased/issue-1327.toml
- src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xTemplates.java
> 4.3 Backport: Fix field parsing for Global Protect 9.1.3 template

- changelog/unreleased/issue-1172.toml
- changelog/unreleased/issue-1318.toml
- changelog/unreleased/issue-780.toml
- src/main/java/org/graylog/integrations/notifications/types/SlackEventNotification.java
- src/main/java/org/graylog/integrations/notifications/types/SlackEventNotificationConfig.java
- src/main/java/org/graylog/integrations/notifications/types/SlackEventNotificationConfigEntity.java
- src/main/java/org/graylog/integrations/notifications/types/SlackMessage.java
- src/main/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsEventNotification.java
- src/main/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsEventNotificationConfig.java
- src/main/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsEventNotificationConfigEntity.java
- src/test/java/org/graylog/integrations/notifications/types/SlackEventNotificationTest.java
- src/test/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsEventNotificationTest.java
- src/web/event-notifications/event-notification-details/SlackNotificationDetails.jsx
- src/web/event-notifications/event-notification-details/SlackNotificationDetails.tsx
- src/web/event-notifications/event-notification-details/TeamsNotificationDetails.tsx
- src/web/event-notifications/event-notification-types/SlackNotificationForm.jsx
- src/web/event-notifications/event-notification-types/SlackNotificationForm.tsx
- src/web/event-notifications/event-notification-types/SlackNotificationSummary.jsx
- src/web/event-notifications/event-notification-types/SlackNotificationSummary.tsx
- src/web/event-notifications/event-notification-types/TeamsNotificationForm.tsx
- src/web/event-notifications/event-notification-types/TeamsNotificationSummary.tsx
- src/web/event-notifications/types.ts
- Support time zones for Slack and Teams notifications (closes #1318)
- Date times included in notifications should now be formatted with the configured time zone
- Default time zone of UTC provided for existing notifications should ensure backwards compatibility
- Adds option to omit the title portion of a Slack notification to reduce clutter (closes #1172)
- Convert existing JSX files to TSX files - does not include a conversion to functional components.
- Also removed a seemingly unused `graylog_url` config property
- Add support for notifying `@here` in Slack notifications instead of just `@channel` (closes #780)
- Note that support is for EITHER channel OR here, not both
All of these changes should be backwards compatible and test successfully with existing MS Teams and Slack …
> Slack and MS Teams Notification Improvements

- src/web/aws/AWSInputConfiguration.jsx
- src/web/aws/cloudwatch/CloudWatch.jsx
- src/web/aws/cloudwatch/CloudWatch.test.jsx
Fixes a navigation issue that was causing a race condition where the HOC was expecting a modal view as a form. This input mounts a component that redirects the user to the stepper form view, unmounting the HOC, preventing the call to `this._openModal` on the `onClick` event for the `Lunc new input` button.
/nocl
> fix(1334): use navigate in useEffect hook

- changelog/unreleased/pr-1340.toml
- src/main/java/org/graylog/integrations/IntegrationsModule.java
- src/main/java/org/graylog/integrations/dataadapters/GreyNoiseCommunityIpLookupAdapter.java
- src/main/java/org/graylog/integrations/dataadapters/GreyNoiseQuickIPDataAdapter.java
- src/main/java/org/graylog/integrations/migrations/V20230522201200_NotificationForDeprecatedGreyNoiseCommunityDataAdapters.java
- src/main/java/org/graylog/integrations/migrations/V20230522201200_RemoveGreyNoiseCommunityDataAdapters.java
- src/web/dataadapters/GreyNoiseAdapterSummary.jsx
- src/web/dataadapters/GreyNoiseCommunityIpLookupAdapterDocumentation.jsx
- src/web/index.jsx
Removes some functionality for the various Data Adapters to limit Graylog's usage of the GreyNoise API. See https://github.com/Graylog2/graylog-plugin-enterprise/issues/5157 for more details.
- Deprecates GreyNoise Community IP Lookup Data Adapter
- Disallows creation of new GreyNoise Community Data Adapter
- Removes ability to start or perform lookups for existing Adapters
- Adds migration that creates a system notification to warn users with existing Adapters of the above
- Removes ability to start or perform lookups for GreyNoise Quick IP Adapters with API tokens that are only associated with a GreyNoise community subscription
In sister PR https://github.com/Graylog2/graylog-plugin-enterprise-integrations/pull/1059:
- Removes ability to start or perform lookups for GreyNoise Full IP …
> Deprecate GreyNoise Data Adapters

- changelog/unreleased/issue-1341.toml
- src/main/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsEventNotification.java
- src/main/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsMessage.java
Adds a summary field with the event definition title to Microsoft Teams notifications. This makes notifications within teams more useful.
Before:
After:
closes #1341
> Add summary field to Microsoft Teams notifications

- changelog/unreleased/issue-1341.toml
Realized while making backport PRs that I messed up the PR number in the changelog
> Fix changelog PR typo in most recent changelog

- changelog/unreleased/issue-1341.toml
- src/main/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsEventNotification.java
- src/main/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsMessage.java
> Backport 5.1: Add summary to teams adaptive card

- .github/ISSUE_TEMPLATE/bug_report.md
Changing the bug/feature templates to ask for the OpenSearch version instead of Elasticsearch.
/nocl
> Changing the GitHub templates to ask for OpenSearch version
